core_right:
  - "Mbuti.DG"
  - "Russia_Ust_Ishim.DG"
  - "China_Tianyuan"
  - "ANE"
  - "Israel_Natufian"
  - "WHG"
  - "Iran_Mesolithic_BeltCave_noUDG"
  - "EHG"
  - "Serbia_IronGates_Mesolithic"
  - "Mongolia_North_N"

target: "Iran_ShahrISokhta_BA2_TWO_I11456_enhanced"

sources:
  -
    - "ONGE.SG"
    - "Laos_Hoabinhian.SG"  
  -
    - "Iran_GanjDareh_N"
    - "Iran_Wezmeh_N.SG"
  -
    - "TTK"
    - "CHN_Tarim_EMBA1"
    - "WSHG"
  -
    - "Turkey_N"
    - "Turkey_Boncuklu_N"
    - "Levant_PPN"